---
collections:
  - name: ansible.windows
    type: galaxy
    version: 1.14.0
  - name: community.windows
    type: galaxy
    version: 1.13.0
  - name: awx.awx
    type: galaxy
    version: 19.2.0
