---
galaxy_info:
  role_name: cleanup_dir
  description: A role to safely clean up directories with proper checks and error handling
  author: KMD-AEVEN-TOOLS
  min_ansible_version: 2.9
  platforms:
    - name: Linux
      versions:
        - all

dependencies: []
