- name: 'A.0.0 Create OS groups'
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: 'A.0.1 Create OS group'
      group_by:
        key: 'machine_{{ ostype }}'
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: 'A.0.1 Socks tunnel setup'
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
    - set_fact:
        ansible_job_id: '{{ tower_job_id }}'
        ansible_become_method: runas
        ansible_become_user: system
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
# get credentials and launch job_template
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: 'A.1.0 set ro execute on cacf localhost'
  hosts: localhost
  gather_facts: false
  become: false
  run_once: true
  ignore_errors: yes
  tasks:
  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  # task
  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: 'A.1.2 launch {{ launch_template_name }} '
      shell: >
        python get_credentials_and_launch_template.py
        -t '{{ launch_template_name }}'
        -n '{{ nodename }}'
        -s '{{ change }}'
      args:
        chdir: "scripts/"
      register: script_result_launch
        # no_log: true

    - name: 'A.1.3 Output result'
      debug:
        var: script_result_launch.stdout_lines
