# filepath: d:\scripts\GIT\KMD-AEVEN-TOOLS\de-tooling_cleanup_CACF_linux.yml
---
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step: begin and setup tunnel and credentials
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '1.A - Create OS groups'
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: '1.A.00 - Create OS group'
      group_by:
        key: "machine_{{ ostype }}"
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: '2.B - Socks tunnel setup'
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - name: '2.B.00 - Set become method and user'
      set_fact:
        ansible_become_method: runas
        ansible_become_user: system
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step working on localhost
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '3.C - Gather facts localhost'
  hosts: localhost
  gather_facts: true
  vars:
  tasks:
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    #step debug facts and list local directories for ansible localhost
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: '3.C.00 - Debug facts and list local directories for ansible localhost'
      block:
        - name: '3.C.01 - Debug facts'
          debug:
            msg: |-
              '{{ ansible_facts }}'
          tags:
            - debug_facts

        - name: '3.C.02 - List homedir files'
          shell: 'ls -lrt'
          register: script_homedir

        - name: '3.C.03 - Output list homedir'
          debug:
            var: script_homedir.stdout_lines

        - name: '3.C.04 - List /tmp/'
          shell: 'ls -lrt /tmp/'
          register: script_tmp

        - name: '3.C.05 - Output list tmp'
          debug:
            var: script_tmp.stdout_lines
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#
#step we are now running from remote host
#
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '4.D - Cleanup ansible / CACF files on host'
  hosts: '{{ nodename }}'
  gather_facts: false
  become: true
  run_once: true
  ignore_errors: yes
  vars:
    nodename: '{{ nodename }}'
    ansib_user1: 'kmduxat1'
    ansib_user2: 'kmduxat2'
    cacfdir: '/var/opt/ansible'
  tasks:
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    #step cleanup ansible / CACF files on host
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: '4.D.00 - Cleanup ansible files on host {{ nodename }}'
      block:
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #
        #step cleanup ansible
        #
        # '/var/opt/ansible/GTS',
        # '/var/opt/ansible/tmp',
        # '/var/opt/ansible/GTS/dataLake'
        #
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '4.D.01 - Check if the {{ cacfdir }} exists'
          ignore_errors: yes
          stat:
            path: '{{ cacfdir }}'
          register: file_stat_CACF

        - name: '4.D.02 - Set {{ cacfdir }} permissions'
          ignore_errors: yes
          become: true
          file:
            path: '{{ cacfdir }}'
            mode: 0775
            owner: root
            group: root
            recurse: true
          when: file_stat_CACF.stat.exists

        - name: '4.D.03 - Test if {{ cacfdir }} is a mountpoint using shell command'
          ignore_errors: yes
          shell: "findmnt -n {{ cacfdir }} > /dev/null 2>&1 && echo 'is_mount' || echo 'not_mount'"
          register: file_mountpoint_CACF
          when: file_stat_CACF.stat.exists

        - name: '4.D.03a - Display mountpoint status'
          debug:
            msg: "Path {{ cacfdir }} is a mountpoint: {{ 'is_mount' in file_mountpoint_CACF.stdout }}"
          when: file_stat_CACF.stat.exists and file_mountpoint_CACF.stdout is defined

        - name: '4.D.04 - Delete {{ cacfdir }}'
          ignore_errors: yes
          become: true
          file:
            path: '{{ cacfdir }}'
            state: absent
            mode: 0775
            owner: root
            group: root
            force: true
          register: delete_dir_result
          when:
            - file_stat_CACF.stat.exists
            - not ('is_mount' in file_mountpoint_CACF.stdout | default(''))

        - name: '4.D.04a - Check what is locking {{ cacfdir }}/ directory'
          shell: "/usr/sbin/lsof +D {{ cacfdir }}/"
          register: locking_processes
          ignore_errors: yes
          when:
            - delete_dir_result.failed
            - file_stat_CACF.stat.exists
            - not ('is_mount' in file_mountpoint_CACF.stdout | default(''))

        - name: '4.D.04b - Display locking processes for {{ cacfdir }}/'
          debug:
            msg: >-
              "No locking processes found for {{ cacfdir }}/" if locking_processes.stdout_lines | length == 0 else locking_processes.stdout_lines
          when:
            - delete_dir_result.failed
            - locking_processes is defined

        - name: '4.D.04c - List {{ cacfdir }}/'
          ignore_errors: yes
          shell: 'ls -lrta {{ cacfdir }}/'
          register: list_agentdir_out
          when:
            - delete_dir_result.failed
            - file_stat_CACF.stat.exists
            - not ('is_mount' in file_mountpoint_CACF.stdout | default(''))

        - name: '4.D.04d - Send output to ansible'
          ignore_errors: yes
          debug:
            var: list_agentdir_out.stdout_lines
          when:
            - delete_dir_result.failed
            - file_stat_CACF.stat.exists
            - not ('is_mount' in file_mountpoint_CACF.stdout | default(''))

        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #step find system components
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '4.D.05 - Find BigFix'
          shell: 'find / -iname "bigfix" 2>/dev/null'
          register: find_result
          changed_when: false
          failed_when: false

        - name: '4.D.05a - Check if BigFix was found'
          debug:
            msg: "BigFix found"
          when: find_result.stdout | trim != ""

        - name: '4.D.06 - Find BESClient ignore case'
          shell: 'find / -iname "BESClient" 2>/dev/null'
          register: find_result_BESClient
          changed_when: false
          failed_when: false

        - name: '4.D.06a - Check if BESClient was found'
          debug:
            msg: "BESClient found"
          when: find_result_BESClient.stdout | trim != ""

        - name: '4.D.08 - Find ansible ignore case'
          shell: 'find / -name "ansible" 2>/dev/null'
          register: find_result_ansible
          changed_when: false
          failed_when: false

        - name: '4.D.08a - Check if ansible was found'
          debug:
            msg: "Ansible found"
          when: find_result_ansible.stdout | trim != ""

        - name: '4.D.09 - Find ILMT ignore case'
          shell: 'find / -name "ILMT" 2>/dev/null'
          register: find_result_ILMT
          changed_when: false
          failed_when: false

        - name: '4.D.09a - Check if ILMT was found'
          debug:
            msg: "ILMT found"
          when: find_result_ILMT.stdout | trim != ""

        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #step remove ansible users ansib_user1
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '4.D.10 - Check if {{ ansib_user1 }} already exists'
          shell: 'id {{ ansib_user1 }}'
          register: unix_user1_info
          changed_when: false
          failed_when: false

        - name: '4.D.11 - Cleanup for user {{ ansib_user1 }}'
          when: unix_user1_info.rc == 0
          block:
            - name: '4.D.11a - Kill all processes owned by {{ ansib_user1 }}'
              shell: "pkill -9 -u {{ ansib_user1 }} || true"
              ignore_errors: true

            - name: '4.D.11b - Remove mail spool for {{ ansib_user1 }}'
              file:
                path: "/var/mail/{{ ansib_user1 }}"
                state: absent
              ignore_errors: true

            - name: '4.D.11c - Remove temp files for {{ ansib_user1 }}'
              shell: "find /tmp -user {{ ansib_user1 }} -exec rm -rf {} \\; 2>/dev/null || true"
              ignore_errors: true

            - name: '4.D.11d - Remove cron jobs for {{ ansib_user1 }}'
              file:
                path: "/var/spool/cron/{{ ansib_user1 }}"
                state: absent
              ignore_errors: true

            - name: '4.D.11e - Remove print jobs for {{ ansib_user1 }}'
              shell: "find /var/spool/cups -user {{ ansib_user1 }} -exec rm -rf {} \\; 2>/dev/null || true"
              ignore_errors: true

            - name: '4.D.11f - Delete user {{ ansib_user1 }}'
              user:
                name: '{{ ansib_user1 }}'
                remove: '{{ data.remove_user_dirs | default(true) }}'
                state: absent
              ignore_errors: true

            - name: '4.D.11g - Delete sudoers profile for {{ ansib_user1 }}'
              file:
                path: '/etc/sudoers.d/{{ ansib_user1 }}_sudo'
                state: absent
              ignore_errors: true

            - name: '4.D.11h - Delete home directory for {{ ansib_user1 }} if it still exists'
              file:
                path: '/home/{{ ansib_user1 }}'
                state: absent
                force: true
              ignore_errors: true

            - name: '4.D.11i - Remove any other sudoers files for {{ ansib_user1 }}'
              shell: "find /etc/sudoers.d/ -name '*{{ ansib_user1 }}*' -exec rm -f {} \\; 2>/dev/null || true"
              ignore_errors: true

            - name: '4.D.11j - Check for remaining files owned by {{ ansib_user1 }}'
              shell: "find / -user {{ ansib_user1 }} -ls 2>/dev/null || true"
              register: remaining_files
              ignore_errors: true
              changed_when: false

            - name: '4.D.11k - Display any remaining files'
              debug:
                msg: "Remaining files for {{ ansib_user1 }}: {{ remaining_files.stdout_lines }}"
              when: remaining_files.stdout_lines | length > 0

        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #step remove ansible users ansib_user2
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '4.D.12 - Check if {{ ansib_user2 }} already exists'
          shell: 'id {{ ansib_user2 }}'
          register: unix_user2_info
          changed_when: false
          failed_when: false

        - name: '4.D.13 - Cleanup for user {{ ansib_user2 }}'
          when: unix_user2_info.rc == 0
          block:
            - name: '4.D.13a - Kill all processes owned by {{ ansib_user2 }}'
              shell: "pkill -9 -u {{ ansib_user2 }} || true"
              ignore_errors: true

            - name: '4.D.13b - Remove mail spool for {{ ansib_user2 }}'
              file:
                path: "/var/mail/{{ ansib_user2 }}"
                state: absent
              ignore_errors: true

            - name: '4.D.13c - Remove temp files for {{ ansib_user2 }}'
              shell: "find /tmp -user {{ ansib_user2 }} -exec rm -rf {} \\; 2>/dev/null || true"
              ignore_errors: true

            - name: '4.D.13d - Remove cron jobs for {{ ansib_user2 }}'
              file:
                path: "/var/spool/cron/{{ ansib_user2 }}"
                state: absent
              ignore_errors: true

            - name: '4.D.13e - Remove print jobs for {{ ansib_user2 }}'
              shell: "find /var/spool/cups -user {{ ansib_user2 }} -exec rm -rf {} \\; 2>/dev/null || true"
              ignore_errors: true

            - name: '4.D.13f - Delete user {{ ansib_user2 }}'
              user:
                name: '{{ ansib_user2 }}'
                remove: '{{ data.remove_user_dirs | default(true) }}'
                state: absent
              ignore_errors: true

            - name: '4.D.13g - Delete sudoers profile for {{ ansib_user2 }}'
              file:
                path: '/etc/sudoers.d/{{ ansib_user2 }}_sudo'
                state: absent
              ignore_errors: true

            - name: '4.D.13h - Delete home directory for {{ ansib_user2 }} if it still exists'
              file:
                path: '/home/{{ ansib_user2 }}'
                state: absent
                force: true
              ignore_errors: true

            - name: '4.D.13i - Remove any other sudoers files for {{ ansib_user2 }}'
              shell: "find /etc/sudoers.d/ -name '*{{ ansib_user2 }}*' -exec rm -f {} \\; 2>/dev/null || true"
              ignore_errors: true

            - name: '4.D.13j - Check for remaining files owned by {{ ansib_user2 }}'
              shell: "find / -user {{ ansib_user2 }} -ls 2>/dev/null || true"
              register: remaining_files_2
              ignore_errors: true
              changed_when: false

            - name: '4.D.13k - Display any remaining files'
              debug:
                msg: "Remaining files for {{ ansib_user2 }}: {{ remaining_files_2.stdout_lines }}"
              when: remaining_files_2.stdout_lines | length > 0
