- name: Create OS groups
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: Create OS group
      group_by:
        key: "machine_{{ ostype }}"
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: Socks tunnel setup
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - set_fact:
        ansible_become_method: runas
        ansible_become_user: system

# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#
#
#
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: 'disable SCCM services'
  hosts: '{{ nodename }}'
  become: true
  gather_facts: false
  vars:
  tasks:
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    # disable block
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: disable block
      block:
        # Check if SCCM service is already disabled
        - name: "Check SCCM service status"
          run_once: true
          win_shell: Get-Service "CcmExec" -ErrorAction SilentlyContinue | Select-Object -Property Name, Status, StartType
          register: SCCM_service_status
          ignore_errors: true

        - name: "Display current SCCM service status"
          debug:
            msg: "Current SCCM service status: {{ SCCM_service_status.stdout }}"

        - name: "Skip disabling if already disabled"
          set_fact:
            skip_disable: "{{ 'Disabled' in SCCM_service_status.stdout }}"

        - name: "Show skip status"
          debug:
            msg: "Service is already disabled, skipping disable operation"
          when: skip_disable | default(false)
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        # disable all SCCM services
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: "Stop and disable SCCM service"
          win_service:
            name: CcmExec
            state: stopped
            start_mode: disabled
          when: not skip_disable | default(false)
          register: service_disabled

        - name: "Display service disable results"
          debug:
            msg: "SCCM service stopped and disabled successfully"
          when: service_disabled is changed

        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        # disable all SCCM services
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: "list CcmExec services"
          run_once: true
          win_shell: Get-Service "CcmExec" -ErrorAction SilentlyContinue | format-list *
          register: SCCM_services_list
        - name: "Display SCCM_services_list"
          debug:
            msg: |-
              "SCCM_services_list: {{ SCCM_services_list.stdout }}"
