# filepath: d:\scripts\GIT\KMD-AEVEN-TOOLS\de-tooling_cleanup_CACF_linux.yml
---
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step: begin and setup tunnel and credentials
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '1.A - Create OS groups'
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: '1.A.00 - Create OS group'
      group_by:
        key: "machine_{{ ostype }}"
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: '2.B - Socks tunnel setup'
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - name: '2.B.00 - Set become method and user'
      set_fact:
        ansible_become_method: runas
        ansible_become_user: system
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Using our new reusable gather_facts_localhost role instead of inline tasks
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '3.C - Gather facts localhost (using role)'
  hosts: localhost
  gather_facts: true
  vars:
    show_debug_facts: false
  tasks:
    - name: '3.C.00 - Include gather_facts_localhost role'
      include_role:
        name: gather_facts_localhost
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step we are now running at remote host
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '4.D - Cleanup ansible / CACF files on host'
  hosts: '{{ nodename }}'
  gather_facts: false
  become: true
  run_once: true
  ignore_errors: yes
  vars:
    nodename: '{{ nodename }}'
    ansib_user1: 'kmduxat1'
    ansib_user2: 'kmduxat2'
    # SSH connection timeout settings to avoid disconnection during long-running operations
    ansible_ssh_timeout: 60
    ansible_persistent_connect_timeout: 180
    ansible_connection_timeout: 180
    ansible_ssh_args: '-o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o ControlMaster=auto -o ControlPersist=180s'
    # Explicitly set Ansible temporary directory to avoid conflicts
    ansible_remote_tmp: /tmp/ansible-safe-tmp
    cleanup_directories:
      - path: '/var/opt/ansible'
        description: 'CACF Directory'
      - path: '/var/opt/ansible_workdir'
        description: 'Ansible Workdir'
      - path: '/etc/ansible'
        description: 'Ansible Configuration'
      - path: '/root/.ansible_async'
        description: 'Ansible Async Directory'
      - path: '/tmp/gts-ansible'
        description: 'GTS Ansible Temp Directory'

  tasks:    # Create safe temporary directory for Ansible operations
    # - name: '4.D.00 - Ensure safe temporary directory exists'
    #   file:
    #     path: "/tmp/ansible-safe-tmp"
    #     state: directory
    #     mode: '0777'
    #   ignore_errors: true

    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    #step cleanup ansible / CACF files on host
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: '4.D.01 - Cleanup ansible directories on host {{ nodename }}'
      include_role:
        name: cleanup_dir
      vars:
        cleanup_path: "{{ item.path }}"
        dir_mode: "0775"
        dir_owner: "root"
        dir_group: "root"
        force_delete: true
        lsof_command: "/usr/sbin/lsof"
      loop: "{{ cleanup_directories }}"
      loop_control:
        label: "{{ item.description }} ({{ item.path }})"
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    #step remove ansible users
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: '4.D.10 - Define list of users to clean up'
      set_fact:
        users_to_cleanup:
          - username: '{{ ansib_user1 }}'
            description: 'Ansible User 1 (kmduxat1)'
          - username: '{{ ansib_user2 }}'
            description: 'Ansible User 2 (kmduxat2)'

    - name: '4.D.11 - Cleanup and remove users'
      include_role:
        name: remove_user_cleanup
      vars:
        username: "{{ item.username }}"
        remove_home: true
        force_removal: true
        handle_locked_processes: true
        check_remaining_files: true
      loop: "{{ users_to_cleanup }}"
      loop_control:
        label: "Removing {{ item.description }}"
      # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
      #step Find cleanup candidates
      # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: '4.D.12 - find cleanup candidates'
      include_role:
        name: find_cleanup_candidates
      vars:
        search_patterns:
          - name: "BigFix"
            pattern: "bigfix"
            case_sensitive: false
          - name: "BESClient"
            pattern: "BESClient"
            case_sensitive: false
          - name: "ITM"
            pattern: "ITM"
            case_sensitive: true
          - name: "Ansible"
            pattern: "ansible"
            case_sensitive: true
          - name: "ILMT"
            pattern: "ILMT"
            case_sensitive: true
        search_path: "/"
        exclude_dirs:
          - "/proc"
          - "/sys"
          - "/dev"
          - "/run"
        output_format: "detailed"
        save_to_file: true
        results_file: "/tmp/cleanup_candidates_{{ ansible_date_time.date }}.txt"

    - name: "4.D.13 - Copy file cleanup_candidates from target host (src) to ansible tower local host (dest)"
      copy:
        src: "/tmp/cleanup_candidates_{{ ansible_date_time.date }}.txt"
        dest: "/tmp/cleanup_candidates_{{ ansible_date_time.date }}.txt"
        remote_src: yes
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step push collected to repository
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
# - name: '7.G - Push cleanup candidates file back to Git repository'
#   include_role:
#     name: git_operations
#   vars:
#     git_repo_url: "{{ git_repository_url | default('https://github.kyndryl.net/eu-nordic-kmn/KMD-AEVEN-TOOLS.git') }}"
#     git_branch: "{{ git_branch | default('main') }}"
#     git_user_name: "Ansible Tower"
#     git_user_email: "ansible@tower.local"
#     git_credentials_method: "{{ git_auth_method | default('https_token') }}"
#     git_token: "{{ git_access_token | default('') }}"
#     local_repo_path: "/tmp/kmd_aeven_tools_repo"
#     files_to_commit:
#       - source: "/tmp/cleanup_candidates_{{ ansible_date_time.date }}.txt"
#         dest: "cleanup_results/{{ inventory_hostname }}_cleanup_candidates.txt"
#         required: false
#     commit_message: "Added cleanup candidates from {{ inventory_hostname }} - {{ ansible_date_time.date }}"

# - name: '8.H - Push cleanup candidates to Git repository'
#   include_tasks: 'roles/push_cleanup_results.yml'
#   vars:
#     git_repository_url: "https://github.kyndryl.net/eu-nordic-kmn/KMD-AEVEN-TOOLS.git"  # Change to your actual repository URL
#     git_branch: "main"                                                                  # Change if your branch is different
#     git_user: "git_cred_tools"                                                          # Your Git username
#     git_token: "{{ lookup('env', 'GIT_TOKEN') }}"                                       # Access token from environment variable
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step - final display system facts and information to confirm cleanup
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '9.I - Final system information collection'
  hosts: localhost
  gather_facts: true
  tasks:
    - name: '9.I.00 - Collect and display final system state'
      include_role:
        name: gather_facts_localhost
      vars:
        show_debug_facts: false  # Set to true if you need detailed facts
        collect_mountpoints: true
        save_to_file: true
        output_dir: "cleanup_results/final_state"