- name: Create OS groups
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: Create OS group
      group_by:
        key: "machine_{{ ostype }}"
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: Socks tunnel setup
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost

- name: Verify de-tooling
  hosts: '{{ nodename }}'
  gather_facts: false
  tasks:
    - include_role:
        name: verify_de-tooling
        apply:
          check_mode: false
          run_once: true
          delegate_to: '{{ nodename }}'
