- name: 'A.0.0 Create OS groups'
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: 'A.0.1 Create OS group'
      group_by:
        key: 'machine_{{ ostype }}'
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: 'A.0.1 Socks tunnel setup'
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - set_fact:
        ansible_job_id: '{{ tower_job_id }}'
        ansible_become_method: runas
        ansible_become_user: system
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
# get credentials and launch job_template
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: 'A.1.0 set ro execute on cacf localhost'
  hosts: localhost
  gather_facts: false
  become: false
  run_once: true
  ignore_errors: yes
- name: 'launch of flow to de-tooling of servers to be handed over to Aeven'
  hosts: '{{ hostlist }}'
  become: true
  gather_facts: false
  vars:
    launch_template_name_01: 'kmn_jobtemplate_de-tooling_maintenancemode'
    launch_template_name_02: 'kmn_jobtemplate_de-tooling_install_itm6_windows'

  tasks:
  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  # task
  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: 'A.1.2 launch {{ launch_template_name_01 }} '
      shell: >
        python get_credentials_and_launch_template.py
        -t '{{ launch_template_name_01 }}'
        -n '{{ nodename }}'
        -s '{{ change }}'
      args:
        chdir: "scripts/"
      register: script_result_launch_01
        # no_log: true

    - name: 'A.1.3 Output result 01'
      debug:
        var: script_result_launch_01.stdout_lines
  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  # task
  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: 'A.1.2 launch {{ launch_template_name_01 }} '
      shell: >
        python get_credentials_and_launch_template.py
        -t '{{ launch_template_name_01 }}'
        -n '{{ nodename }}'
        -s '{{ change }}'
      args:
        chdir: "scripts/"
      register: script_result_launch_01
        # no_log: true

    - name: 'A.1.3 Output result 01'
      debug:
        var: script_result_launch_01.stdout_lines