---
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step: begin and setup tunnel and credentials
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '1.A - Create OS groups'
  hosts: '{{ nodename }}'
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: '1.A.00 - Create OS group'
      group_by:
        key: 'machine_{{ ostype }}'
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: '2.B - Socks tunnel setup'
  hosts: '{{ nodename }}'
  gather_facts: false
  tasks:
    - include_role: # Not numbered per rules
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: '{{ blueid_shortcode }}'
        transaction_id: '{{ tower_job_id }}'
        trans_num: '{{ tower_job_id }}'

    - name: '2.B.00 - Set become user'
      set_fact:
        ansible_become_user: root

# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#step:  uninstall ITM on linux, and then cleanup
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: '3.C - uninstall ITM on linux, and then cleanup'
  hosts: '{{ nodename }}'
  become: true
  gather_facts: false
  tasks:
    - name: '3.C.00 - Copy, create, fetch file block'
      block:
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #step:  Copy, create, fetch file
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '3.C.01 - Create prtemp_dir directory'
          file:
            path: /tmp/scripttemp_dir
            state: directory
            mode: 0777

        - name: '3.C.02 - copy multiple items'
          copy:
            src: '{{ item.src }}'
            dest: '{{ item.dest }}'
            mode: 0777

          loop:
            - src: scripts/ITMAgentUNinstall_linux.pl
              dest: /tmp/scripttemp_dir/ITMAgentUNinstall_linux.pl

        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #step:  run uninstall
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '3.C.03 - Run command'
          shell: perl -w ITMAgentUNinstall_linux.pl -d
          args:
            chdir: /tmp/scripttemp_dir
          register: script_run

        - name: '3.C.04 - Output list'
          debug:
            var: script_run.stdout_lines

        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #step:  Delete ITM files
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '3.C.05 - Delete /opt/IBM/ITM/ directory'
          file:
            path: /opt/IBM/ITM/
            state: absent

        - name: '3.C.06 - List /opt/IBM/ITM/'
          ignore_errors: yes
          shell: 'ls -lrta /opt/IBM/ITM/'
          register: list_agentdir_out

        - name: '3.C.07 - send output to ansible'
          debug:
            var: list_agentdir_out.stdout_lines

        - name: '3.C.08 - Delete scripttemp_dir directory'
          ignore_errors: yes
          file:
            path: /tmp/scripttemp_dir
            state: absent

        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        #step:  remove itmuser
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: '3.C.09 - Check if itmuser exists'
          shell: 'grep -i "^itmuser:" /etc/passwd'
          register: unix_user_info
          ignore_errors: true
          changed_when: false

        - name: '3.C.10 - send output to ansible'
          debug:
            var: unix_user_info.stdout_lines
          when:
            - unix_user_info.rc == 0
            - unix_user_info.stdout is match("itmuser")

        - name: '3.C.11 - Delete user itmuser'
          ignore_errors: true
          user:
            name: 'itmuser'
            remove: '{{ data.remove_user_dirs | default(true) }}'
            state: absent
          when:
            - unix_user_info.rc == 0
            - unix_user_info.stdout is match("itmuser")

        - name: '3.C.12 - list /etc/sudoers.d/itm*'
          ignore_errors: yes
          shell: 'ls -lrta /etc/sudoers.d/itm*'
          register: list_agentdir_out
          when:
            - unix_user_info.rc == 0
            - unix_user_info.stdout is match("itmuser")

        - name: '3.C.13 - Delete sudoers profile for itmuser'
          ignore_errors: true
          ansible.builtin.file:
            path: "/etc/sudoers.d/itmuser_sudo"
            state: absent

        - name: '3.C.14 - Additional task example'
          debug:
            msg: "This is a placeholder for the next task."