- name: Create OS groups
  hosts: '{{ hostlist }}'
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: Create OS group
      group_by:
        key: 'machine_{{ ostype }}'
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: Socks tunnel setup
  hosts: 'machine_windows'
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: '{{ blueid_shortcode }}'
        transaction_id: '{{ tower_job_id }}'
        trans_num: '{{ tower_job_id }}'

    - set_fact:
        ansible_become_method: runas
        ansible_become_user: system

# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#
# The whole playbook is running from ansible tower host
#
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: 'Export of on host from ansible itower inventory and then remove the host from all inventories'
  hosts: localhost
  gather_facts: false
  become: false
  run_once: true
  ignore_errors: yes
  vars:
    nodename: '{{ nodename }}'
    tower_host: 'https://ansible-tower-web-svc-tower.apps.kmdcacf001.adminkmd.local'
    # tower_username: 'functional_id_001'
    # tower_password: 'm9AHKuXYa*MeZZWLsHqB'
  tasks:
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Export host from inventory
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: 'A.0.0 Export host from inventory'
      block:
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        # run uninstall using ccmsetup
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: Create tower-cli config
          include_role:
            name: towercli-init

        - name: Run command
          uri:
            url: "{{ tower_host }}/api/v2/hosts/?name={{ nodename }}"
            method: GET
            user: "{{ tower_username }}"
            password: "{{ tower_password }}"
            force_basic_auth: yes
            validate_certs: no
            return_content: yes
          register: host_response
          delegate_to: localhost

        - name: List inventories for the host
          debug:
            msg: "Host {{ nodename }} found in inventory: {{ item.name }}"
          loop: "{{ host_response.json.results[0].summary_fields.inventory.related_groups | default([]) }}"
          when: host_response.json.results | length > 0