- name: Create OS groups
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: Create OS group
      group_by:
        key: "machine_{{ ostype }}"
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: Socks tunnel setup
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - set_fact:
        ansible_become_method: runas
        ansible_become_user: system

# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
#
#
#
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: 'disable SCCM services'
  hosts: '{{ nodename }}'
  become: true
  gather_facts: false
  vars:
  tasks:
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    # disable block
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: disable block
      block:
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        # disable all SCCM services
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: "list CcmExec services"
          run_once: true
          win_shell: Get-Service "CcmExec" -ErrorAction SilentlyContinue | Stop-Service -PassThru | Set-Service -StartupType disabled
          # win_shell: Get-Service "CcmExec" -ErrorAction SilentlyContinue | Set-Service -StartupType Manual -PassThru | Start-Service
          register: SCCM_services_stop
        - name: "Display SCCM_services_stop"
          debug:
            msg: |-
              "SCCM_services_stop: {{ SCCM_services_stop.stdout }}"

      # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        # disable all SCCM services
        # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
        - name: "list CcmExec services"
          run_once: true
          win_shell: Get-Service "CcmExec" -ErrorAction SilentlyContinue | format-list *
          register: SCCM_services_list
        - name: "Display SCCM_services_list"
          debug:
            msg: |-
              "SCCM_services_list: {{ SCCM_services_list.stdout }}"
