- name: 'A.0.0 Create OS groups'
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: 'A.0.1 Create OS group'
      group_by:
        key: 'machine_{{ ostype }}'
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: 'A.0.1 Socks tunnel setup'
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - set_fact:
        ansible_job_id: '{{ tower_job_id }}'
        ansible_become_method: runas
        ansible_become_user: system
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
# get credentials and launch job_template
# -----------------------------------------------------------------------------------------------------------------------------------------------------------------
- name: 'A.1.0 launch of flow to de-tooling of servers to be handed over to Aeven'
  hosts: localhost
  gather_facts: false
  become: false
  run_once: true
  ignore_errors: yes
  vars:
    launch_template_name_00:  'kmn_jobtemplate_de-tooling_set_maintenancemode'
    launch_template_name_01:  'kmn_jobtemplate_de-tooling_cleanup_CACF_ansible'
    launch_template_name_02:  'kmn_jobtemplate_de-tooling_disable_SCCM_windows'
    launch_template_name_03:  'kmn_jobtemplate_de-tooling_servercheck_windows'
    launch_template_name_04W: 'kmn_jobtemplate_de-tooling_UNinstall_ITM_windows'
    launch_template_name_04L: 'kmn_jobtemplate_de-tooling_UNinstall_ITM_linux'
  tasks:
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Always runn launch_template_name_00
    # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: 'A.1.1 launch {{ launch_template_name_00 }} '
      shell: >
        python launch_and_misc_awx_functions.py
        -t '{{ launch_template_name_00 }}'
        -n '{{ nodename }}'
        -s '{{ change }}'
      args:
        chdir: "scripts/"
      register: script_result_launch_00
        # no_log: true

    - name: 'A.1.3 Output result 00'
      debug:
        var: script_result_launch_00.stdout_lines

  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  # {{ launch_template_name_01 }}
  # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
    - name: 'A.1.1 launch {{ launch_template_name_01 }} '
      shell: >
        python launch_and_misc_awx_functions.py
        -t '{{ launch_template_name_01 }}'
        -n '{{ nodename }}'
        -s '{{ change }}'
      args:
        chdir: "scripts/"
      register: script_result_launch_01
        # no_log: true

    - name: 'A.1.3 Output result 01'
      debug:
        var: script_result_launch_01.stdout_lines

  # # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  # # {{ launch_template_name_02 }}
  # # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  #   - name: 'A.1.2 launch {{ launch_template_name_02 }} '
  #     shell: >
  #       python launch_and_misc_awx_functions.py
  #       -t '{{ launch_template_name_02 }}'
  #       -n '{{ nodename }}'
  #       -s '{{ change }}'
  #     args:
  #       chdir: "scripts/"
  #     register: script_result_launch_02
  #       # no_log: true

  #   - name: 'A.1.3 Output result 02'
  #     debug:
  #       var: script_result_launch_01.stdout_lines

  # # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  # # {{ launch_template_name_03 }}
  # # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  #   - name: 'A.1.2 launch {{ launch_template_name_03 }} '
  #     shell: >
  #       python launch_and_misc_awx_functions.py
  #       -t '{{ launch_template_name_03 }}'
  #       -n '{{ nodename }}'
  #       -s '{{ change }}'
  #     args:
  #       chdir: "scripts/"
  #     register: script_result_launch_03
  #       # no_log: true

  #   - name: 'A.1.3 Output result 03'
  #     debug:
  #       var: script_result_launch_01.stdout_lines

  # # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  # # {{ launch_template_name_04 }}
  # # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  #   - name: 'A.1.2 launch {{ launch_template_name_04 }} '
  #     shell: >
  #       python launch_and_misc_awx_functions.py
  #       -t '{{ launch_template_name_04 }}'
  #       -n '{{ nodename }}'
  #       -s '{{ change }}'
  #     args:
  #       chdir: "scripts/"
  #     register: script_result_launch_04
  #       # no_log: true

  #   - name: 'A.1.3 Output result 04'
  #     debug:
  #       var: script_result_launch_01.stdout_lines