- name: Create OS groups
  hosts: "{{ hostlist }}"
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: Create OS group
      group_by:
        key: "machine_{{ ostype }}"
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: Socks tunnel setup
  hosts: 'machine_windows'
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - set_fact:
        ansible_become_method: runas
        ansible_become_user: system
        
- name: Get script result on windows nodes
  hosts:  "{{ hostlist }}"
  become: true
  run_once: true
  ignore_errors: yes      
  gather_facts: false
  vars:
      # aeven_logfile           = f"{contentDir}/serverConfigScanner_aeven_logfile.trc" # collected from the host: the transcript
      # aeven_fstdout           = f"{contentDir}/serverConfigScanner_aeven_fstdout.log" # collected from the host: the stdout - if any
      # aeven_foutcsv           = f"{contentDir}/serverConfigScanner_aeven_foutcsv.csv" # collected from the host: the OS/Computer info collected on the host
      # aeven_fsrvcsv           = f"{contentDir}/serverConfigScanner_aeven_fsrvcsv.csv" # collected from the host: the services found on host
      # aeven_fsftcsv           = f"{contentDir}/serverConfigScanner_aeven_fsftcsv.csv" # collected from the host: the software found on host

      tmpdir: "C:/Windows/Temp/persistent_check/"
      cmdexec: "serverConfigScanner.ps1"  
      aeven_logfile: "serverConfigScanner_aeven_logfile.trc"
      aeven_fstdout: "serverConfigScanner_aeven_fstdout.log"
      aeven_foutcsv: "serverConfigScanner_aeven_foutcsv.csv"
      aeven_fsrvcsv: "serverConfigScanner_aeven_fsrvcsv.csv"
      aeven_fsftcsv: "serverConfigScanner_aeven_fsftcsv.csv"
  tasks:
    - name: run check_for_persistent_route
      # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
      # run check_for_persistent_route
      # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
      block:
        - name: copy scripts
          win_copy: 
            src: scripts/
            dest: "{{ tmpdir }}"

        - name: Run powershell
          win_shell: "{{ tmpdir }}{{ cmdexec }} > {{ tmpdir }}{{ aeven_logfile }} 2>&1"
          args:
            chdir: "{{ tmpdir }}"
          register: running_aeven_logfile

        - name: "Read content from aeven_logfile"
          run_once: true
          win_shell: "Get-Content -LiteralPath {{ tmpdir }}{{ aeven_logfile }}"
          register: file_content_aeven_logfile
        - name: "Display content in aeven_logfile"
          debug:
            msg: |-
              "aeven_logfile {{ file_content_aeven_logfile.stdout }}"

           

