- name: Create OS groups
  hosts: "{{ hostlist }}"
  become: false
  gather_facts: false
  connection: local
  tasks:
    - name: Create OS group
      group_by:
        key: "machine_{{ ostype }}"
      changed_when: false
      when: ostype is defined
      delegate_to: localhost

- name: Socks tunnel setup
  hosts: 'machine_windows'
  gather_facts: false
  tasks:
    - include_role:
        name: ansible-role-event-socks-tunnel
        apply:
          check_mode: false
          run_once: true
          delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
        trans_num: "{{ tower_job_id }}"

    - set_fact:
        ansible_become_method: runas
        ansible_become_user: system
        
- name: Get script result on windows nodes
  hosts:  "{{ hostlist }}"
  become: true
  run_once: true
  ignore_errors: yes      
  gather_facts: false
  vars:
      tmpdir: "C:/Windows/Temp/persistent_check/"
      cmdexec: "serverConfigScanner.ps1"  
      foutlog: "serverConfigScanner.log"
      foutcsv: "serverConfigScanner.csv"
      fsrvcsv: "serverConfigScanner_services.csv"
      fsftcsv: "serverConfigScanner_software.csv"
  tasks:
    - name: run check_for_persistent_route
      # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
      # run check_for_persistent_route
      # -----------------------------------------------------------------------------------------------------------------------------------------------------------------
      block:
        - name: copy scripts
          win_copy: 
            src: scripts/
            dest: "{{ tmpdir }}"

        - name: Run powershell
          win_shell: "{{ tmpdir }}{{ cmdexec }} > {{ tmpdir }}{{ foutlog }} 2>&1"
          args:
            chdir: "{{ tmpdir }}"
          register: script_run_persistent

        - name: "Read content from foutlog"
          run_once: true
          win_shell: "Get-Content -LiteralPath {{ tmpdir }}{{ foutlog }}"
          register: file_content_stdout
        - name: "Display content in stdout"
          debug:
            msg: |-
              "aeven_stdout_log {{ file_content_stdout.stdout }}"

        - name: "Read content from foutcsv"
          run_once: true
          win_shell: "Get-Content -LiteralPath {{ tmpdir }}{{ foutcsv }}"
          register: file_content_foutcsv
        - name: "Display content in foutcsv"
          debug:
            msg: |-
              "aeven_foutcsv {{ file_content_foutcsv.stdout }}"
        
        - name: "Read content from fsrvcsv"
          run_once: true
          win_shell: "Get-Content -LiteralPath {{ tmpdir }}{{ fsrvcsv }}"
          register: file_content_fsrvcsv
        - name: "Display content in fsrvcsv"
          debug:
            msg: |-
              "aeven_fsrvcsv {{ file_content_fsrvcsv.fsrvcsv }}"
        
        - name: "Read content from fsftcsv"
          run_once: true
          win_shell: "Get-Content -LiteralPath {{ tmpdir }}{{ fsftcsv }}"
          register: file_content_fsftcsv
        - name: "Display content in fsrvcsv"
          debug:
            msg: |-
              "aeven_fsrvcsv {{ file_content_fsftcsv.stdout }}"
              