---
# Default variables for find_cleanup_candidates role

# List of search patterns to look for
search_patterns:
  - name: "BigFix"
    pattern: "bigfix"
    case_sensitive: false
  - name: "BESClient"
    pattern: "BESClient"
    case_sensitive: false
  - name: "ITM"
    pattern: "ITM"
    case_sensitive: true
  - name: "Ansible"
    pattern: "ansible"
    case_sensitive: true
  - name: "ILMT"
    pattern: "ILMT"
    case_sensitive: true

# Where to search (default is entire filesystem)
search_path: "/"

# Whether to record file details (like permissions, size, etc.)
include_file_details: false

# Maximum search depth
max_depth: 20

# Exclude directories from search
exclude_dirs:
  - "/proc"
  - "/sys"
  - "/dev"
  - "/run"

# Output format (simple, detailed, or json)
output_format: "detailed"

# Save results to file
save_to_file: false
results_file: "/tmp/cleanup_candidates.txt"
