-----BEGIN CERTIFICATE-----
MIIFEzCCA/ugAwIBAgIQfQLlzpweTJGscZW/hwrWOjANBgkqhkiG9w0BAQsFADCB
wjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlTdW5ueXZhbGUx
FTATBgNVBAoTDE9wc3dhcmUgSW5jLjEVMBMGA1UECxMMT3Bzd2FyZSBUZWFtMSIw
IAYJKoZIhvcNAQkBFhNzdXBwb3J0QG9wc3dhcmUuY29tMRUwEwYDVQQDEwxib290
c3RyYXAtY2ExKTAnBgNVBAUTIDdkMDJlNWNlOWMxZTRjOTFhYzcxOTViZjg3MGFk
NjM5MB4XDTIwMDEwNzA5MDgwNFoXDTMwMDEwNTA5MDgwNFowgZQxCzAJBgNVBAYT
AlVTMQswCQYDVQQIEwJDQTESMBAGA1UEBxMJU3Vubnl2YWxlMRUwEwYDVQQKEwxP
cHN3YXJlIEluYy4xFTATBgNVBAsTDE9wc3dhcmUgVGVhbTESMBAGA1UEAxMJYm9v
dHN0cmFwMSIwIAYJKoZIhvcNAQkBFhNzdXBwb3J0QG9wc3dhcmUuY29tMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtoVfIaIlb89J3r3X0Xr9kGFJbwPg
cptYlQquq3m2/JiCbkI8XBqhW1lW99y6Rz0d4ZqrLP6zOtwGmCTGte6MyI6j47Z6
PXjfBhQe41CwjudSECoHaj9gmjexwk0OUc4Si+CYqFnq71yeyGWh2XjDyVhSGGol
W9y5mGT0XNxrGxrdkylox94Bkqiecc7DjFgF+MDhI3DrVrGWPvtdma7fCQjkYb0/
PtbB9KEWY3DO6jiczLLYXmvgb4MQcDQrlwilFeiZmVjqIJ/o3YfQinCGQVu6ySnr
za0ed++Sj4Qj0hjDupa2Le+8tAN+U9XOmy0ka2cYMeliKCUQl6wh2oKqJQIDAQAB
o4IBLzCCASswCQYDVR0TBAIwADAdBgNVHQ4EFgQU380/BDmPJQyf5fYVqYGyBOmX
GKAwgf4GA1UdIwSB9jCB84AUDc+XoooFx44Kjcye/+V+V0EKkOyhgcikgcUwgcIx
CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTESMBAGA1UEBxMJU3Vubnl2YWxlMRUw
EwYDVQQKEwxPcHN3YXJlIEluYy4xFTATBgNVBAsTDE9wc3dhcmUgVGVhbTEiMCAG
CSqGSIb3DQEJARYTc3VwcG9ydEBvcHN3YXJlLmNvbTEVMBMGA1UEAxMMYm9vdHN0
cmFwLWNhMSkwJwYDVQQFEyA3ZDAyZTVjZTljMWU0YzkxYWM3MTk1YmY4NzBhZDYz
OYIQfQLlzpweTJGscZW/hwrWOTANBgkqhkiG9w0BAQsFAAOCAQEAZSLdoNhe1Dq/
S+JvyRDMe0nmqPA5C5J8v7y67EcWvYPoUWcWNXweG1AXoqyIVOLpO2f8sLWxKUkb
iW+O1IipMXwALYPZ7EI2Lhhlv9BKXlCGAAuqFMqkuPvMtSHj0Y7jUcweMoll0ECE
YBdjMEwPjqmYk6Xh79kAAeTtpSHxLt9xDs+20GO54fm6NmOqSIzxhma7vDAn0Zpv
JoT43Kg+hj1LFA/ErEWLSdIySkXW82Qlf7tPF1NAnLfqk3VFO246XRCEyVc1ErGq
CIOqlju3VeVkZuGrtQ4ikatZmcm9mJlBozxru3dSWRNez7tP5IDY+BblWzUMC3ZX
jgGJGRz64w==
-----END CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAtoVfIaIlb89J3r3X0Xr9kGFJbwPgcptYlQquq3m2/JiCbkI8
XBqhW1lW99y6Rz0d4ZqrLP6zOtwGmCTGte6MyI6j47Z6PXjfBhQe41CwjudSECoH
aj9gmjexwk0OUc4Si+CYqFnq71yeyGWh2XjDyVhSGGolW9y5mGT0XNxrGxrdkylo
x94Bkqiecc7DjFgF+MDhI3DrVrGWPvtdma7fCQjkYb0/PtbB9KEWY3DO6jiczLLY
Xmvgb4MQcDQrlwilFeiZmVjqIJ/o3YfQinCGQVu6ySnrza0ed++Sj4Qj0hjDupa2
Le+8tAN+U9XOmy0ka2cYMeliKCUQl6wh2oKqJQIDAQABAoIBAEi6/ryFQ0u5myMC
HTThQJc+3Sc6sT6Z/oNtfUrhNnSTRS4wgKLnDbM793bPYv8uMHEM0/cbC0qCELKh
vPkUNM9aX55GwZErUBu4+tHz/lcDgGTmiovg81qgpNnbIMCiUCui9NHo+sAk9TS/
ou3ovIPICPannXlsjBxY5jL2tktXDfr1m5bOGYyMCqtjdXgy0pDhGrsyynPQ81uL
KhxTXpWG4guMsBK77WCCG2eHV7j7eUdR6oGi6YBj9hMgWt6wp2mT+SU18x8Iyn1R
GthNb6O+UBHp7aGOCayj5PGwYPaU99Gbw/KgIjjieTLWnYh1bjVGPYkzs/bmIRjB
MGgFssUCgYEA2eR7atqEh35WTpwXeErIiPQZmrWTq/C7yh1UB369dCEtMyaYtENE
8wxJpCVgwcsVjocwEwTgnBDxiX+DIJuRH5WdNjN5LjJDQfyNJAac/N1+EiOi9rV+
SZzaBZxPss7Nme+3w/kJOUhfV2V3kfpvAMwidP87pFRBffiO3LJB4BcCgYEA1nE6
308Yo0EsX3dQViuC2tf5uvE07+RD5QGQYa/13nPHWIz6pkJ+JwzQI54m9TqhwRsf
IxGi63wH+D/2atVlwgBxUWhzf4lGv05r7Ir1wkEdi6DK3aa4BPOTZyeO9D5HF1aE
ChKXAR8dIKd+5+lSryXxvzXDo6r9o285kbmMkSMCgYEA1WJZr0JCqcKC2UcqAOcT
znNnI8iQzsDZ10yzfweSl8jpz/8LavW571/oOnVUdVTiTot7/BQ5tv0s3d/fVa6k
B89of60XDrOwhE3FFzPWyBhNn4wAyyTggUy3gukab9zxIsDNMYGQk+WZYSiAWZhs
3tYLJJLUINFWtfwWRHHZ648CgYASkNcSAl0VtUzMLx5Ld5TqsYwzfTKiGlcueoYv
jvZwfgGiTwJcZqFZbCiRDN4+mQbsGxcFCD/ct25RNeh1s2gN9c/ZxntJbW8snPOH
FTjVyqFuN0uZCRghhZ0bbzdXOhUZlin0XUupkzIIY7f/CBpag6R8c4EuqF0xSy3m
yfO7lQKBgDlMnmakPZNdH/Pfvp7ZE1HAECHgQi3QOHdQRgnSILSgMZC4FQobDB6k
JhZ68WmvJ8LWez9GbRfysR2jkALRoxeOcPbjEhduf/Tho1AwG5CmUbXL+YyCsoS9
hovk09kW+uDT0go+7aPHM8W4HSldSojaEzozGxFGfpUfKV3DhROR
-----END RSA PRIVATE KEY-----
