---
- name: "2.A2.1. Check if a backup is running"
  ansible.builtin.shell: ps -ef | grep -v grep | grep "dsmc inc"
  register: backup_check
  failed_when:
    - backup_check.rc >= 2

- name: "2.A2.2. A backup is already running, exit"
  ansible.builtin.debug:
    msg: A backup is already running, exit
  when:
    - backup_check.rc == 0
  failed_when:
    - backup_check.rc == 0

- name: "2.A2.3. Run final backup - dsmc inc"
  ansible.builtin.command: "dsmc inc"
  register: dsmc_output
  async: 7200
  poll: 0
  when:
    - backup_check.rc == 1

- name: "2.A2.4. Waiting for backup completion"
  async_status:
    jid: "{{ dsmc_output.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 120
  delay: 60
  when:
    - backup_check.rc == 1

- name: "2.A2.5. Backup failed, exit"
  ansible.builtin.debug:
    msg: Backup failed, exit
  when:
    - backup_check.rc == 1
    - job_result.rc != 0
    - job_result.rc != 4
    - job_result.rc != 8
  failed_when:
    - job_result.rc != 0
    - job_result.rc != 4
    - job_result.rc != 8

- name: "2.A2.6. Print job results"
  ansible.builtin.debug:
    msg: "{{ job_result }}"
