---
- name: "2.A2.A1. Disable TLS 1.0. Step 1."
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: Enabled
    data: 0
    type: dword
  when: data.task_type in ["KMDAUT5001", "KMDAUT5002", "KMDAUT5003", "KMDAUT5004"]

- name: "2.A2.A2. Disable TLS 1.0. Step 2."
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
    name: DisabledByDefault
    data: 1
    type: dword
  when: data.task_type in ["KMDAUT5001", "KMDAUT5002", "KMDAUT5003", "KMDAUT5004"]

- name: "2.A2.A3. Disable TLS 1.1. Step 1."
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: Enabled
    data: 0
    type: dword
  when: data.task_type in ["KMDAUT5001", "KMDAUT5002", "KMDAUT5003", "KMDAUT5004"]

- name: "2.A2.A4. Disable TLS 1.1. Step 2."
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
    name: DisabledByDefault
    data: 1
    type: dword
  when: data.task_type in ["KMDAUT5001", "KMDAUT5002", "KMDAUT5003", "KMDAUT5004"]

- name: "2.A2.A5. Update registry key property TLS 1.2\\Server\\DisabledByDefault to value 0 (dword)"
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
    name: DisabledByDefault
    data: 0
    type: dword
  when: data.task_type in ["KMDAUT5002", "KMDAUT5003"]

- name: "2.A2.A6. Update registry key property TLS 1.3\\Server\\DisabledByDefault to value 0 (dword)"
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server
    name: DisabledByDefault
    data: 0
    type: dword
  when: data.task_type in ["KMDAUT5002", "KMDAUT5004"]
