---
galaxy_info:
  name: user_delete
  author: FirstName LastName <firstname.lastname@domain.com>
  description: PIM User Management - Delete User
  min_ansible_version: 2.9
  galaxy_tags:
    - user_management
  platforms:
    - name: GenericWindows
      versions:
        - any
# TODO: Include argument spec when Ansible Core 2.11 is released
dependencies: {}
