---
- name: "2.A2.1. Update {{ data.username }}"
  ansible.windows.win_user:
    name: "{{ data.username }}"
    password: "{{ data.password | default(omit) }}"
    fullname: "{{ data.fullname | default(omit) }}"
    description: "{{ data.description | default('') }}"
    home_directory: "{{ (data.home is defined and data.homedrive is defined) | ternary((data.homedrive | default(omit))+(data.home | default(omit)), omit) }}"
    login_script: "{{ data.logonscript | default(omit) }}"
    profile: "{{ data.profile | default(omit) }}"
    password_expired: "{{ data.expired is defined | ternary((data.expired | default(omit)) | bool, omit) }}"
    account_disabled: "{{ data.account_disabled is defined | ternary((data.account_disabled | default(omit)) | bool, omit) }}"
    account_locked: "{{ data.unlock_account is defined | ternary((not data.unlock_account | default(omit)) | bool, omit) }}"
    password_never_expires: "{{ data.password_never_expires is defined | ternary((data.password_never_expires | default(omit)) | bool, omit) }}"
    user_cannot_change_password: "{{ data.disallow_change_password is defined | ternary((data.disallow_change_password | default(omit)) | bool, omit) }}"
    state: present
  failed_when: data.username is not defined
  register: win_user_info
