---
# tasks/main.yml for ssh_connectivity role
# This role ensures SSH connectivity to remote hosts

- name: 'Ensure SSH directory exists locally'
  file:
    path: "~/.ssh"
    state: directory
    mode: '0700'
  delegate_to: localhost

- name: 'Check if SSH key exists'
  stat:
    path: "~/.ssh/id_rsa"
  register: ssh_key_exists
  delegate_to: localhost

- name: 'Generate SSH key if not exists'
  shell: 'ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""'
  when: not ssh_key_exists.stat.exists
  delegate_to: localhost

- name: 'Set host key checking to false'
  lineinfile:
    path: "~/.ssh/config"
    line: "Host {{ inventory_hostname }}\n  StrictHostKeyChecking no"
    create: yes
    mode: '0600'
  delegate_to: localhost

- name: 'Check target connectivity'
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    timeout: 10
  ignore_errors: yes
  register: ssh_connectivity
  delegate_to: localhost

- name: 'Display SSH connectivity status'
  debug:
    msg: "SSH connectivity to {{ inventory_hostname }} is {{ 'available' if ssh_connectivity.state is defined else 'unavailable' }}"

- name: 'Ensure safe temp directory exists on target'
  file:
    path: "/tmp/ansible-{{ ansible_user }}-{{ ansible_date_time.epoch }}"
    state: directory
    mode: '0700'
  ignore_errors: yes
